### PR TITLE
Arrow functions

### PR DESCRIPTION
**Pull request by msfidelis**

### CODE REVIEW

**Comment by hoegertn** [comment]
Why did you remove all the semicolons?

**Comment by gpotter2** [comment]
Hello all,
As this is getting ridiculous, ans as @ashiina seems to be completly inactive, could you re-do this PR on https://github.com/gpotter2/lambda-local ? I'll be updating the code with all other PRs...

Thank you !

**Comment by ashiina** [comment]
Hi thanks for the PR!
1. Removing semicolons are irrelevant to the arrow function, and I do not want to remove them without a real objective. Could you please put the semicolons back in?
2. We have recently merged a large change, so can you resolve the conflict with the new `develop` branch?

Thanks!

**Comment by ashiina** [comment]
@gpotter2 Asking for your opinion: I believe the arrow function has its benefits. Do you think it is worth cutting Node.js 1.8 for this change (1.8 does not support arrow functions, and the build is failing as a result)?

**Comment by hoegertn** [comment]
The minimum version in AWS Lambda is 4.3, so I think it is no problem to use this version as a base version for lambda-local too.

**Comment by gpotter2** [comment]
I'm ok with the changes (except semicolons).

I would like this to wait a bit, so we could have a last version working with 0.18 without bugs. So next version won't have this.

**Comment by msfidelis** [comment]
I'll fix this on this weekend. Thanks a lot!

**Pull request closed without merging**
