### PR TITLE
`context.memoryLimitInMB` is a string

### PR DESCRIPTION
**Pull request by armanbilge**
See:
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9035bba65ea608e5ac12f7f23b8b6a07e600865f/types/aws-lambda/handler.d.ts#L99
- https://github.com/netlify/functions/pull/251#issuecomment-997858750

Thanks!

### CODE REVIEW

**Comment by gpotter2** [comment]
Thanks for the PR. I'll try to release this ASAP (today?)

**Comment by armanbilge** [comment]
Thanks for the fast response. That would be fantastic, much appreciated! :)

**Comment by gpotter2** [comment]
Shipped in 2.0.1

**Comment by armanbilge** [comment]
Wonderful, thank you!

**Pull request merged**
