### PR TITLE
added support for environment variables

### PR DESCRIPTION
**Pull request by rodgersTR**
Added support for user-supplied environment variables with flag -E, which takes a JSON string of key/value pairs.

### CODE REVIEW

**Comment by QAnders** [comment]
Thanks much needed, but as I tried the code but I get an error from it:

`error: uncaughtException: Unexpected token u in JSON at position 0 date=Mon Jan 16 2017 09:18:47 GMT+0100 (Romance Standard Time), pid=16696, uid=null, gid=null, cwd=D:\nodejs\node_modules\qip-lambda-company-search, execPath=C:\Program Files\nodejs\node.exe, version=v7.1.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\F2518230\AppData\Roaming\npm\node_modules\lambda-local\bin\lambda-local], rss=24141824, heapTotal=10465280, heapUsed=5639048, loadavg=[0, 0, 0], uptime=311672.4529456, trace=[column=null, file=null, function=JSON.parse, line=null, method=parse, native=false, column=22, file=C:\Users\F2518230\AppData\Roaming\npm\node_modules\lambda-local\bin\lambda-local, function=null, line=50, method=null, native=false, column=3, file=C:\Users\F2518230\AppData\Roaming\npm\node_modules\lambda-local\bin\lambda-local, function=, line=109, method=null, native=false, column=32, file=module.js, function=Module._compile, line=573, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=582, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=490, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=449, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=441, method=Module._load, native=false, column=10, file=module.js, function=Module.runMain, line=607, method=runMain, native=false, column=7, file=bootstrap_node.js, function=run, line=420, method=null, native=false], stack=[SyntaxError: Unexpected token u in JSON at position 0,     at JSON.parse (<anonymous>),     at C:\Users\F2518230\AppData\Roaming\npm\node_modules\lambda-local\bin\lambda-local:50:22,     at Object.<anonymous> (C:\Users\F2518230\AppData\Roaming\npm\node_modules\lambda-local\bin\lambda-local:109:3),     at Module._compile (module.js:573:32),     at Object.Module._extensions..js (module.js:582:10),     at Module.load (module.js:490:32),     at tryModuleLoad (module.js:449:12),     at Function.Module._load (module.js:441:3),     at Module.runMain (module.js:607:10),     at run (bootstrap_node.js:420:7)]`

**Comment by QAnders** [comment]
Might just be a Windows issue when running from CMD. Also JSON with double quotes not working either so I changed the following for running on Windows in lambda-local file line 44 added and then replace for single quote to double quote:

`if(!program.environment) program.environment = '{}';
	
    var eventPath = program.eventPath,
        lambdaPath = program.lambdaPath,
        lambdaHandler = program.handler,
        profilePath = program.profilePath,
        profileName = program.profile,
        region = program.region,
		environment = JSON.parse(program.environment.replace(/\'/g, '\"')),
        callbackWaitsForEmptyEventLoop = program.noForceCallback;`

Using single quotes in Windows CMD call now, e.g. `-E "{'single': 'quotes'}"`

**Comment by razbomi** [comment]
Why not use something dotenv instead?
Then environment variables can be specified in a file.

https://www.npmjs.com/package/dotenv

**Comment by roeyazroel** [comment]
+1 any change of merging it anytime soon? :)

**Comment by ashiina** [comment]
Sorry for not merging this. Looks good, will merge!

**Pull request merged**
