### PR TITLE
AWS Profile and Region (#26) management, Reverce -c (#39), mute feature, new lambda signature, documentation 

### PR DESCRIPTION
**Pull request by HerveNivon**
1. Add AWS profile name management
2. Add default AWS_REGION (see #26)
3. Reverse -c option (see #39)
4. Review Unix like options
5. Implement the optional callback 3rd parameter in the lambda handler's signature
6. Change the value of process.exit based on success or failure
7. Add possibility to mute console.log, this is useful for calling in a mocha test suite for instance
8. Review code, variables' names and "use strict";
9. Add license field in package.json
10. Update README.md and add documentation for calls in other node.js programs

### CODE REVIEW

**Comment by HerveNivon** [comment]
On `nodejs` 0.10 and 0.12 build fails because of `const` keyword.

**Comment by HerveNivon** [comment]
We can even simplify credentials loading dropping the `--profile-path` option and using the AWS SDK http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html

`var creds = new AWS.SharedIniFileCredentials({profile: 'myprofile'});
AWS.config.credentials = creds;`

**Comment by gpotter2** [comment]
This will conflict with other PRs but should be prioritized

**Comment by HerveNivon** [comment]
Thx @gpotter2

**Comment by ashiina** [comment]
Hey thanks for the PR! Looks great. Thanks for all the changes. The code is a lot cleaner. 

But in the future, I'd appreciate it if you can submit a PR for coding style changes in a different PR. Since almost every line has a diff, it makes it very difficult to review. 
I've taken enough time to look over this one so don't worry about this PR. Thanks again!

**Comment by ashiina** [comment]
Also thanks @gpotter2 for the other PR! Sounds like this was something many people wanted fixed.

**Comment by gpotter2** [comment]
By the way, your editor is messing with the indent... Using two spaces instead of four is really uncommon (and should be illegal 😄 )

**Pull request merged**
