### PR TITLE
add execute function using promises

### PR DESCRIPTION
**Pull request by hoegertn**

### CODE REVIEW

**Comment by ashiina** [comment]
Great feature! I love this.
One concern I have is that, I want the exposed API to be as simple as possible. 
It would be better if developers do not have to choose between `execute` and `executePromised`

Cool solutions to this may be: 
 * `execute` will automatically try to fall back to `promise` if `callback` isn't defined in the parameter.
 * `execute` just takes an `asPromise` flag as a parameter

Would like to hear your opinions on this @hoegertn @gpotter2

**Comment by gpotter2** [comment]
I would prefer to set it as a fallback rather than a flag, as it would be weird to have two separate exits (promise and callback at the same time)

**Comment by hoegertn** [comment]
Sounds good. I will try to implement the fallback solution.

**Comment by hoegertn** [comment]
@ashiina @gpotter2 I changed it as requested. Now a promise is returned when the options do not contain a callback

**Comment by ashiina** [comment]
Awesome!!

**Comment by ashiina** [comment]
Really elegant coding too. Thanks a lot for this contribution!

**Pull request merged**
