### PR TITLE
lambda-local should understand the new async handler syntax

### PR DESCRIPTION
**Pull request by hoegertn**

### CODE REVIEW

**Comment by gpotter2** [comment]
Thanks a lot for you PR !

**Comment by hoegertn** [comment]
Thanks for merging! Any idea when this will be released? This prevents using the new features as the tests are red.

**Comment by gpotter2** [comment]
I can release it right now !
Will push that in a minute

**Comment by hoegertn** [comment]
Thanks, that is really fast :+1:

**Comment by gpotter2** [comment]
1.4.7 is out!

**Pull request merged**
