### PR TITLE
Fix Lambda ending rules

### PR DESCRIPTION
**Pull request by baipi**
Lambda should success if given `err` in `context.done` or `callback` is `null` or `undefined`.

[Doc AWS:](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html#nodejs-prog-model-handler-callback)
```
callback();     // Indicates success but no information returned to the caller.
callback(null); // Indicates success but no information returned to the caller.
callback(null, "success");  // Indicates success with information returned to the caller.
callback(error);    //  Indicates error with error information returned to the caller.
```

### CODE REVIEW

**Comment by gpotter2** [comment]
Thanks so much for this PR,
very good job !

**Comment by MartinBieth** [comment]
Thank you, that was much needed ! Can you update npm @gpotter2 ?

**Comment by gpotter2** [comment]
I can't :/ I'm gonna ask @ashiina to do so

**Comment by gpotter2** [comment]
I can now, updated !

**Pull request merged**
