### PR TITLE
Log final error returned by lamdbaLocal execute

### PR DESCRIPTION
**Pull request by QB3L**
While testing one of my lambdas found myself wanting to log the final error instead of having to log stuff myself in the lambda method. Thought this might be useful

### CODE REVIEW

**Comment by QB3L** [comment]
@ashiina just looking through my open PRs and noticed this. Do you want to merge this or should I close it?

**Comment by gpotter2** [comment]
Hey, it looks like @ashiina has not been online for a while :/ please let this open.
If he still isn't online for the next month, I'll create a new "official" fork of the repo I guess...

**Comment by QB3L** [comment]
Thanks @gpotter2 just let me know if you do fork it so we can work together and I can keep contributing. I have more changes I've done locally while working with this and want to contribute some of those as well as I think it would be helpful for other users.

**Comment by gpotter2** [comment]
Thanks :)

**Comment by hoegertn** [comment]
Sounds great, happy to help here too.

**Comment by gpotter2** [comment]
Hello all,
As this is getting ridiculous, ans as @ashiina seems to be completly inactive, could you re-do this PR on https://github.com/gpotter2/lambda-local ? I'll be updating the code with all other PRs...

Thank you !

**Comment by QB3L** [comment]
Closing as we are moving to gpotter fork

**Pull request closed without merging**
