### PR TITLE
fixed logger object

### PR DESCRIPTION
**Pull request by ashiina**
fix for https://github.com/ashiina/lambda-local/issues/54

### CODE REVIEW

**Comment by gpotter2** [comment]
Can you add:
```
winston.add(winston.transports.Console, {handleExceptions: true, json: false, colorize: true})
```
And see if it breaks anything ?
Cause if it works, it will configure the logger for a console type, which is better...

**Comment by ashiina** [comment]
@gpotter2 I tried the following fix:

```
 (function() {
 
-       var logger = require('winston');
-       logger.level = 'info';
+    var logger = require('winston');
+    logger.level = 'info';
+    logger.add(logger.transports.Console, {handleExceptions: true, json: false, colorize: true});
 
```

And got this

```
$ node ./bin/lambda-local 
Error: Transport already attached: console, assign a different name
```

So it sounds like the default is `Console` ?

**Comment by gpotter2** [comment]
Yes, but colorize it set to false...
Found something else:
```
  winston.configure({
    transports: [
      new (winston.transports.Console)({handleExceptions: true, json: false, colorize: true})
    ]
  });
```

**Comment by ashiina** [comment]
@gpotter2 I was looking for updating transport instead of adding a new one. I think your proposal is a good fix! Please wait a moment while I write correct tests for this

**Comment by ashiina** [comment]
@gpotter2 Great, it's working without any warnings! Will include this in the PR

**Comment by gpotter2** [comment]
@ashiina great !

**Comment by ashiina** [comment]
@gpotter2 This is my final state of the PR, can you quickly review it and check for any problems?

**Comment by andrewkboyd** [comment]
@ashiina, I just ran a test with this and seems to be working well.

This was my first time using lambda-local and I thought I was doing something wrong! Thanks for the quick turnaround

**Comment by ashiina** [comment]
@andrewkboyd Thanks and sorry for the bug! Will merge and make a new release

**Pull request merged**
